### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by DannyBen** [jafarlihi/rssnix#2]
Any plans to release binaries?

**Comment by jafarlihi** [comment]
I'll try to set up GitHub Actions pipeline later, no promises though.
Also, there's now AUR package available.

**Comment by DannyBen** [comment]
I have seen people use [goreleaser](https://goreleaser.com/) a lot.

**Comment by jafarlihi** [comment]
@DannyBen Thanks! Did set it up, now there's binary releases.
