### ISSUE TITLE
ERRO[0000] Failed to create a file for article titled

### ISSUE THREAD

**Issue by bl00dy1837** [jafarlihi/rssnix#4]
I tested some RSS feeds. The feed https://blog.fefe.de/rss.xml is mostly failing. 
Maybe to long or wrong encoding? Didn't dive into the code yet :smile: .

**Comment by jafarlihi** [comment]
Thanks for reporting. I'll look into it sometime within this week.

**Comment by mattpep** [comment]
I've raised an MR to fix this, and included some simple tests with it too.
